### ISSUE TITLE
 No log system exists

### ISSUE THREAD

**Issue by shijinkui** [webx/citrus#13]
maven 3.1.1
webx-all-in-one  3.0.6

slf4j的冲突？

换成maven 3.0.5就OK了

```

Execution default of goal com.alibaba.citrus.tool:maven-autoconfig-plugin:1.0.10:autoconfig failed: No log system exists -> [Help 1]

```

**Comment by FrankFang** [comment]
居然把 maven-autoconfig-plugin 改名为 autoconfig-maven-plugin， so ugly.

**Comment by superbaobao** [comment]
这个是maven的要求。maven-xxxx-plugin被保留为maven内部使用，而外部插件一律使用xxxx-maven-plugin。

谢谢。
