### ISSUE TITLE
ajax 提交form 无法验证表单

### ISSUE THREAD

**Issue by iamchenney** [webx/citrus#20]
$.post(
                "$testModule.setTarget('test_form/edit_form.do')",
                $('#editForm').serialize(),
                function(data,status){
                     alert(status);
                }
        );
这样提交表单不进行验证？

**Comment by superbaobao** [comment]
验证是在服务器端进行的，和你如何提交表单无关。

你只需要关注一下，（用类似firebug工具）POST出去的数据是怎样的。表单的验证是你在screen/action中取得form/group/field对象时发生。如果你的action方法的参数中有诸如@Group()之类的注解，那么它就会自动取得表单数据并验证。

如果不验证，你得看看：1. action有没有被调用（取决于action参数和event_submit_do_xxx参数） 2. 有没有相关的annotations?

周

**Comment by iamchenney** [comment]
非常感谢baobao，这么快就回复了！！！
我看了一下，form是验证了的，但是screen的方法肯定会执行，导致我之前以为form没有进行验证。不好意思啊；
但是还有个问题 如何把验证信息返回给页面，我理解是要自己在doEditForm中把form的验证信息取出来，用json返回？是这样吗
