### ISSUE TITLE
webx中form表单的验证取值问题

### ISSUE THREAD

**Issue by ytzhangFTD** [webx/citrus#24]
如果一个form表单中既有需要进行验证的属性，又包含不需要验证的属性，该表单里的所有属性都必须要在对应的form.xml文件中配置么？如果不想配置不要验证的属性，有什么好的解决办法么？

**Comment by superbaobao** [comment]
如果你要把表单数据注入到bean中，那么最好在form.xml中定义field，但不定义validators即可。
